[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
async-stream = "0.3.6"
async-trait = "0.1.86"
aws-config = "1.5.16"
aws-sdk-bedrockruntime = "1.73.0"
axum = "0.8.1"
bedrock = { path = "../bedrock" }
chrono = "0.4.39"
futures = "0.3.31"
request = { path = "../request" }
uuid = { version = "1.13.1", features = ["v4"] }
response = { path = "../response" }
serde_json = "1.0.138"
tracing = "0.1.41"
